def get_ibex35_tickers():
    tickers = {
        "Acciona": "ANA.MC",
        "Acciona Energía": "ANE.MC",
        "Acerinox": "ACX.MC",
        "ACS": "ACS.MC",
        "AENA": "AENA.MC",
        "Amadeus": "AMS.MC",
        "ArcelorMittal": "MTS.MC",
        "Banco Sabadell": "SAB.MC",
        "Bankinter": "BKT.MC",
        "BBVA": "BBVA.MC",
        "CaixaBank": "CABK.MC",
        "Cellnex": "CLNX.MC",
        "Enagás": "ENG.MC",
        "Endesa": "ELE.MC",
        "Ferrovial": "FER.MC",
        "Fluidra": "FDR.MC",
        "Grifols": "GRF.MC",
        "IAG": "IAG.MC",
        "Iberdrola": "IBE.MC",
        "Inditex": "ITX.MC",
        "Indra": "IDR.MC",
        "Colonial": "COL.MC",
        "Logista": "LOG.MC",
        "Mapfre": "MAP.MC",
        "Meliá": "MEL.MC",
        "Merlin": "MRL.MC",
        "Naturgy": "NTGY.MC",
        "Redeia": "RED.MC",
        "Repsol": "REP.MC",
        "Rovi": "ROVI.MC",
        "Sacyr": "SCYR.MC",
        "Santander": "SAN.MC",
        "Solaria": "SLR.MC",
        "Telefónica": "TEF.MC",
        "Unicaja": "UNI.MC"
    }
    print(f"{len(tickers)} empresas del IBEX 35 cargadas")
    return tickers